### PR TITLE
Add modify functions

### PR DESCRIPTION
**Pull request by yofreke**
I wanted to modify my AST and saw that there were no helper utility functions in this library.  I wrote a couple basic ones.
- `glsl.mod.find(node)`
- `glsl.mod.remove(node)`
- `glsl.mod.replace(node, newNode)`
- `glsl.mod.add(node, newNode, after)`
- `glsl.mod.addBefore(node, newNode)`
- `glsl.mod.addAfter(node, newNode)`

### CODE REVIEW

**Comment by lammas** [comment]
Fantastic! :)
Would you be up for writing tests for the mod functions too?

**Comment by yofreke** [comment]
I wrote some basic ones to ensure that they work.  They are not comprehensive.

Side note: might be worth breaking your tests up in to a couple different files d:

**Comment by lammas** [comment]
Yes, breaking them up into manageable bits is long overdue :p

**Comment by lammas** [comment]
Thank you! 
v1.1.0 in npm now.

**Pull request merged**
